---
   tasks:
   - name: installing pkg
     become: true
     ansible.builtin.apt:
      name: apache2
      state: latest
---
- name: download css template
  ansible.builtin.get_url:
   url:
   dest: /var/www/html/
- name    
... 